#!/command/with-contenv bash
#shellcheck shell=bash

# shellcheck disable=SC1091
source /scripts/common
cd /scripts/acars2pos
npm run start 2>&1 | stdbuf -o0 awk '{print "[acars2pos] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
